### PR TITLE
Fix book duplication

### PR DESCRIPTION
**Pull request by louisroyer**
This happened when placing a book on an `itemframes:itemframe` from `homedecor`.
Now books are placed correctly in itemframes and doesn't duplicate anymore.

### CODE REVIEW

**Comment by taikedz** [comment]
Thanks for the fix - is the new behaviour confirmed to remain correct when placing on other items with right click like furnaces, chests, pipes, etc?

**Comment by louisroyer** [comment]
> Thanks for the fix - is the new behaviour confirmed to remain correct when placing on other items with right click like furnaces, chests, pipes, etc?

I updated the branch because the behavior was incorrect for chests. Now it only applies on `wallmounted` nodes having a `on_rightclick`.

**Comment by taikedz** [comment]
OK thanks. I still need to check a couple things on my end to be sure this won't introduce further issues. My feeling is that it is not our role to call the other mod's `on_righclick()` - that responsibility should lie with the event handling itself. On reflection, I would even say, if we detect an `on_rightclick()` on the target object, just treat our operation as an idempotent operation.

The event handling within Minetest should, in fact do this - when you right-click on a furnace, it should call the furnace's `on_rightclick()` and the furnace should indicate that no further processing of the event should be done - in which case, the bug may well be in `itemframe`, not here..... (it's been a long tims since I've thought about Minetest event logic....)

**Comment by louisroyer** [comment]
When you call `minetest.item_place`, this already call `on_rightclick` if defined (see [lua_api.txt](https://github.com/minetest/minetest/blob/71287894adbf3cbe092ded1cbf02755678305afb/doc/lua_api.txt#L5215)) so in my opinion, the call is our responsibility (at least as the engine is currently done). But if you find a better solution, as long as the bug is fixed, this is fine to me.

**Comment by taikedz** [comment]
OK that makes sense...

```
    * Calls `on_rightclick` of `pointed_thing.under` if defined instead
    * **Note**: is not called when wielded item overrides `on_place`
```

I guess this is the part that's relevant to our current situation... What was happening with the chests? My concern is, `wallmounted` might not be the sanity check that would be sufficient for other things... the problem encountered by chests could be triggered by some other arbitrary `wallmounted` item...?

In fact, I thought your original change was in theory fine -- so I am a little surprised that chests highlighted a problem...

**Comment by louisroyer** [comment]
Maybe by using `item_place_node` instead of `item_place` and checking `get_player_control().sneak` like the original [`item_place` does](https://github.com/minetest/minetest/blob/42a9b45c21ad407689950e3a4c90cb3894142260/builtin/game/item.lua#L419), I can avoid the check on `wallmounted`.

**Comment by louisroyer** [comment]
> Maybe by using `item_place_node` instead of `item_place` and checking `get_player_control().sneak` like the original [`item_place` does](https://github.com/minetest/minetest/blob/42a9b45c21ad407689950e3a4c90cb3894142260/builtin/game/item.lua#L419), I can avoid the check on `wallmounted`.

Now the behavior is:
- if you click (or shift-click) on a classic node: it places the book
- if you shift-click on a node having `on_rightclick` : it places the book
- if you click on a node having `on_rightclick`: it calls `on_rightclick` and does not place the book

**Comment by taikedz** [comment]
That looks sane. I don't think I've ever seen a need to code this explicitly, but maybe that's a new behaviour...

In any case, this looks like it mimics the behaviour I expect from normal stuff, so I'm happy. Thank you for your diligent efforts!

**Pull request merged**
